# Task 5: Interactive Business Dashboard (Streamlit)

## Objective
The goal is to build an interactive dashboard to analyze sales, profit, and customer performance.

## Step 1: Data Cleaning and Preparation

In this step, we will:
- Load the dataset
- Check for missing values
- Fix data types
- Prepare data for dashboard usage

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Load dataset
df = pd.read_csv('superstore.csv', sep=',')

# Preview
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [2]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

df.info()

Shape: (51290, 27)

Columns:
['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name', 'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority', 'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID', 'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State', 'Sub.Category', 'Year', 'Market2', 'weeknum']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [3]:
print("Missing Values:\n")
print(df.isnull().sum())

Missing Values:

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [4]:
# Fill missing values (if any)
df.fillna(method='ffill', inplace=True)

In [5]:
# Convert Order Date to datetime
df['Order.Date'] = pd.to_datetime(df['Order.Date'])

# Check again
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  datetime64[ns]
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(6), object(17)
memory usage: 10.6+ MB

In [6]:
print("Total Sales:", df['Sales'].sum())
print("Total Profit:", df['Profit'].sum())

Total Sales: 12642905
Total Profit: 1467457.2912800002

In [7]:
df = df[[
    'Order.Date',
    'Region',
    'Category',
    'Sub.Category',
    'Customer.Name',
    'Sales',
    'Profit'
]]

df.head()

,Order.Date,Region,Category,Sub.Category,Customer.Name,Sales,Profit
0,2011-01-07,West,Office Supplies,Paper,Lycoris Saunders,19,9.3312
1,2011-01-21,West,Office Supplies,Paper,Mark Van Huff,19,9.2928
2,2011-08-05,West,Office Supplies,Paper,Chad Sievert,21,9.8418
3,2011-08-05,West,Office Supplies,Paper,Chad Sievert,111,53.2608
4,2011-09-29,West,Office Supplies,Paper,Arthur Prichep,6,3.1104

## Conclusion (Step 1)

- Dataset was successfully loaded and explored.
- Missing values were handled.
- Data types were corrected (Order Date converted to datetime).
- Relevant columns were selected for dashboard creation.

The dataset is now clean and ready for building the Streamlit dashboard.

In [8]:
!pip install streamlit
import streamlit as st
import pandas as pd

# Page config
st.set_page_config(
    page_title="Business Dashboard",
    layout="wide"
)

# Title
st.title("📊 Sales & Profit Dashboard")
st.markdown("Analyze sales, profit, and customer performance")

Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 61.4 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 104.8 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.56.0

2026-04-13 16:09:57.241 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:09:57.242 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:09:57.394
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-04-13 16:09:57.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:09:57.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:09:57.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:09:57.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:09:57.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [9]:
@st.cache_data
def load_data():
    # Load dataset from the local file which was previously cleaned
    # Ensure to use the correct separator (comma) as identified before
    df_loaded = pd.read_csv('superstore.csv', sep=',')

    # Convert Order Date to datetime, using the correct column name 'Order.Date'
    df_loaded['Order.Date'] = pd.to_datetime(df_loaded['Order.Date'])

    # Select relevant columns as identified in previous steps
    df_processed = df_loaded[[
        'Order.Date',
        'Region',
        'Category',
        'Sub.Category', # Corrected from 'Sub-Category' based on df.columns.tolist()
        'Customer.Name', # Corrected from 'Customer Name' based on df.columns.tolist()
        'Sales',
        'Profit'
    ]]
    return df_processed

df = load_data()

2026-04-13 16:10:00.781 No runtime found, using MemoryCacheStorageManager
2026-04-13 16:10:00.783 No runtime found, using MemoryCacheStorageManager
2026-04-13 16:10:00.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [10]:
st.subheader("Dataset Preview")
st.dataframe(df.head())

2026-04-13 16:10:04.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:04.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:04.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:05.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:05.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:05.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [11]:
# Create columns
col1, col2 = st.columns(2)

with col1:
    st.metric("Total Sales", "Loading...")

with col2:
    st.metric("Total Profit", "Loading...")

2026-04-13 16:10:06.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.453 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.459 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:10:06.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [14]:
!streamlit run app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.24.82.49:8501

  Stopping...

In [63]:
%%writefile app.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ==============================
# PAGE CONFIG
# ==============================
st.set_page_config(
    page_title="Business Dashboard",
    layout="wide"
)

st.title("📊 Sales & Profit Dashboard")
st.markdown("Analyze sales, profit, and customer performance")

# ==============================
# LOAD DATA
# ==============================
@st.cache_data
def load_data():
    # Load dataset from the local file
    df_loaded = pd.read_csv('superstore.csv', sep=',')
    df_loaded['Order.Date'] = pd.to_datetime(df_loaded['Order.Date'])

    # Select relevant columns and correct column names
    df_processed = df_loaded[[
        'Order.Date',
        'Region',
        'Category',
        'Sub.Category', # Corrected from 'Sub-Category'
        'Customer.Name', # Corrected from 'Customer Name'
        'Sales',
        'Profit'
    ]]
    return df_processed

df = load_data()

# ==============================
# SIDEBAR FILTERS
# ==============================
st.sidebar.header("🔍 Filters")

region = st.sidebar.multiselect(
    "Select Region",
    df['Region'].unique(),
    default=df['Region'].unique()
)

category = st.sidebar.multiselect(
    "Select Category",
    df['Category'].unique(),
    default=df['Category'].unique()
)

sub_category = st.sidebar.multiselect(
    "Select Sub-Category",
    df['Sub.Category'].unique(), # Corrected from 'Sub-Category'
    default=df['Sub.Category'].unique()
)

# ==============================
# APPLY FILTERS
# ==============================
filtered_df = df[
    (df['Region'].isin(region)) &
    (df['Category'].isin(category)) &
    (df['Sub.Category'].isin(sub_category)) # Corrected from 'Sub-Category'
]

# ==============================
# KPIs
# ==============================
total_sales = filtered_df['Sales'].sum()
total_profit = filtered_df['Profit'].sum()

col1, col2 = st.columns(2)

with col1:
    st.metric("💰 Total Sales", f"${total_sales:,.2f}")

with col2:
    st.metric("📈 Total Profit", f"${total_profit:,.2f}")

# ==============================
# TOP CUSTOMERS
# ==============================
st.subheader("🏆 Top 5 Customers by Sales")

top_customers = (
    filtered_df.groupby('Customer.Name')['Sales'] # Corrected from 'Customer Name'
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

st.dataframe(top_customers)

# ==============================
# CHARTS
# ==============================

# Sales by Category
sales_by_category = filtered_df.groupby('Category')['Sales'].sum()
fig1, ax1 = plt.subplots()
sales_by_category.plot(kind='bar', ax=ax1)
ax1.set_title("Sales by Category")
st.pyplot(fig1)

# Profit by Region
profit_by_region = filtered_df.groupby('Region')['Profit'].sum()
fig2, ax2 = plt.subplots()
profit_by_region.plot(kind='bar', ax=ax2)
ax2.set_title("Profit by Region")
st.pyplot(fig2)

# Sales over time
sales_over_time = filtered_df.groupby('Order.Date')['Sales'].sum() # Corrected from 'Order Date'
fig3, ax3 = plt.subplots()
sales_over_time.plot(ax=ax3)
ax3.set_title("Sales Over Time")
st.pyplot(fig3)

# ==============================
# FOOTER
# ==============================
st.markdown("---")
st.markdown("### 📌 Dashboard Insights")
st.write("This dashboard helps analyze sales trends, profit performance, and customer contributions.")

Overwriting app.py

In [65]:
st.sidebar.header("🔍 Filters")

region = st.sidebar.multiselect(
    "Select Region",
    options=df['Region'].unique(),
    default=df['Region'].unique()
)

category = st.sidebar.multiselect(
    "Select Category",
    options=df['Category'].unique(),
    default=df['Category'].unique()
)

sub_category = st.sidebar.multiselect(
    "Select Sub-Category",
    options=df['Sub.Category'].unique(),
    default=df['Sub.Category'].unique()
)

2026-04-13 16:45:00.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.337 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.339 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:45:00.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

## View Streamlit App with LocalTunnel

In [66]:
# Install pyngrok for ngrok functionality
!pip install pyngrok

Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (8.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)

In [80]:
from google.colab import userdata

# Attempt to retrieve the NGROK_AUTH_TOKEN from Colab secrets
ngrok_token = userdata.get('NGROK_AUTH_TOKEN')

if ngrok_token:
    print(f"NGROK_AUTH_TOKEN is set. Its value (first 5 chars): {ngrok_token[:5]}...")
else:
    print("NGROK_AUTH_TOKEN is NOT set or not accessible in Colab secrets. Please ensure it's added.")

NGROK_AUTH_TOKEN is set. Its value (first 5 chars): 3CJK7...

In [ ]:
from pyngrok import ngrok
from google.colab import userdata
import os

# Get your ngrok authtoken from Colab secrets
ngrok_token = userdata.get('NGROK_AUTH_TOKEN')

if ngrok_token:
    # Strip any whitespace characters from the token
    ngrok_token = ngrok_token.strip()
    ngrok.set_auth_token(ngrok_token)
    print(f"NGROK_AUTH_TOKEN set successfully (first 5 chars: {ngrok_token[:5]}...)")

    # Disconnect any existing ngrok tunnels
    ngrok.kill()

    # Open a ngrok tunnel to the Streamlit port (8501)
    public_url = ngrok.connect(8501)
    print(f"Streamlit App URL: {public_url}")

    # Run the Streamlit app in the background
    !streamlit run app.py &
else:
    print("NGROK_AUTH_TOKEN is NOT set or not accessible in Colab secrets. Please ensure it's added.")

NGROK_AUTH_TOKEN set successfully (first 5 chars: 3CJK7...)
Streamlit App URL: NgrokTunnel: "https://scope-manger-cosmos.ngrok-free.dev" -> "http://localhost:8501"

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.24.82.49:8501

In [68]:
import os

# Attempt to retrieve the NGROK_AUTH_TOKEN from environment variables
NGROK_AUTH_TOKEN_CHECK = os.environ.get("NGROK_AUTH_TOKEN")

if NGROK_AUTH_TOKEN_CHECK:
    print("NGROK_AUTH_TOKEN is set and accessible. Its value (first 5 chars):", NGROK_AUTH_TOKEN_CHECK[:5] + "...")
else:
    print("NGROK_AUTH_TOKEN is NOT set or not accessible. Please ensure it's added to Colab secrets.")

NGROK_AUTH_TOKEN is NOT set or not accessible. Please ensure it's added to Colab secrets.

In [69]:
import os

# Access the NGROK_AUTH_TOKEN from Colab secrets
NGROK_AUTH_TOKEN = os.environ.get("NGROK_AUTH_TOKEN")

if NGROK_AUTH_TOKEN:
    print("NGROK_AUTH_TOKEN accessed successfully (first 5 chars):", NGROK_AUTH_TOKEN[:5] + "...")
else:
    print("NGROK_AUTH_TOKEN is not set or accessible in Colab secrets.")

NGROK_AUTH_TOKEN is not set or accessible in Colab secrets.

In [70]:
# Apply filters
filtered_df = df[
    (df['Region'].isin(region)) &
    (df['Category'].isin(category)) &
    (df['Sub.Category'].isin(sub_category))
]

In [46]:
total_sales = filtered_df['Sales'].sum()
total_profit = filtered_df['Profit'].sum()

# Top 5 customers
top_customers = (
    filtered_df.groupby('Customer.Name')['Sales']
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

In [47]:
# KPI layout
col1, col2 = st.columns(2)

with col1:
    st.metric("💰 Total Sales", f"${total_sales:,.2f}")

with col2:
    st.metric("📈 Total Profit", f"${total_profit:,.2f}")

2026-04-13 16:37:48.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.558 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [48]:
st.subheader("🏆 Top 5 Customers by Sales")

st.dataframe(top_customers)

2026-04-13 16:37:48.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [49]:
import matplotlib.pyplot as plt

# Group data
sales_by_category = filtered_df.groupby('Category')['Sales'].sum()

# Plot
fig1, ax1 = plt.subplots()
sales_by_category.plot(kind='bar', ax=ax1)

ax1.set_title("Sales by Category")
ax1.set_xlabel("Category")
ax1.set_ylabel("Sales")

st.pyplot(fig1)

2026-04-13 16:37:48.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:48.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [50]:
profit_by_region = filtered_df.groupby('Region')['Profit'].sum()

fig2, ax2 = plt.subplots()
profit_by_region.plot(kind='bar', ax=ax2)

ax2.set_title("Profit by Region")
ax2.set_xlabel("Region")
ax2.set_ylabel("Profit")

st.pyplot(fig2)

2026-04-13 16:37:48.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [51]:
# Time series
sales_over_time = filtered_df.groupby('Order.Date')['Sales'].sum()

fig3, ax3 = plt.subplots()
sales_over_time.plot(ax=ax3)

ax3.set_title("Sales Over Time")
ax3.set_xlabel("Date")
ax3.set_ylabel("Sales")

st.pyplot(fig3)

2026-04-13 16:37:49.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [52]:
col1, col2 = st.columns(2)

with col1:
    st.pyplot(fig1)

with col2:
    st.pyplot(fig2)

st.pyplot(fig3)

2026-04-13 16:37:49.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.913 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:49.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.226 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [53]:
st.markdown("---")

2026-04-13 16:37:50.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [54]:
st.markdown("### 📌 Dashboard Insights")
st.write("This dashboard provides insights into sales performance, profit trends, and top customers.")

2026-04-13 16:37:50.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-13 16:37:50.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

## Final Conclusion

- An interactive Streamlit dashboard was successfully developed.
- Users can filter data based on Region, Category, and Sub-Category.
- Key performance indicators such as Total Sales and Profit are dynamically updated.
- Visualizations provide insights into sales trends and regional performance.

This dashboard helps businesses make data-driven decisions and monitor performance effectively.